### ISSUE TITLE
Any idea how to improve rendering performance ?

### ISSUE THREAD

**Issue by nrcaz** [xcarpentier/rn-pdf-reader-js#103]
Hi,

Nice job, this is the best pdf reader library i found for rn so far, easy to install.
I was wondering if you would have some advice to improve the rendering, i have a client which use really heavy PDF file.
On iOS with the default reader it takes forever, with your library it is slightly better but not enough to be seamless.

Any idea on how i could improve the performance ?

Thanks

**Comment by xcarpentier** [comment]
Please try the latest version, in a decrease package size that may help to improve performance a bit.
