### ISSUE TITLE
How to get total number of pages in pdf?

### ISSUE THREAD

**Issue by mjmanav4** [xcarpentier/rn-pdf-reader-js#104]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* rn-pdf-reader-js version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by wolfAC** [comment]
is it fixed?
