### ISSUE TITLE
Page numbers showing correctly, but PDF not showing

### ISSUE THREAD

**Issue by SheldonReay** [xcarpentier/rn-pdf-reader-js#108]
#### Issue Description

The PDF does not seem to be rendering (it rendered once the first time I ever ran the program with rn-pdf-reader-js installed) but never again. It does **show the correct page numbers** of the PDF. 

#### Steps to Reproduce / Code Snippets

Loading a PDF off a domain that requires a cookie. (the cookie doesnt seem to be an issue as it grabs the correct page numbers)

![Screenshot 2020-06-08 at 18 51 15](https://user-images.githubusercontent.com/53275733/84058416-7ed2a780-a9b9-11ea-9ecb-8a41776da41c.png)
![Screenshot 2020-06-08 at 18 51 37](https://user-images.githubusercontent.com/53275733/84058431-83975b80-a9b9-11ea-84c8-ca5b6f878998.png)

**As you can see here, it has the correct PDF page numbers.**

#### Expected Results

Rendering and Displaying the PDF successfully. 

#### Additional Information

* Nodejs version: v13.13.0
* React version: "~16.9.0",
* React Native version: "~0.61.5",
* rn-pdf-reader-js version: "^3.1.0"
* Platform(s) (iOS, Android, or both?): Android
* TypeScript version: Not using

**Comment by jarvisluong** [comment]
Can this be the incompatible react-native-webview version?

**Comment by xcarpentier** [comment]
Maybe the PDF is too large.
Are you able to use a smaller PDF to isolate the issue?

**Comment by jarvisluong** [comment]
This also happens to me btw but with a local downloaded pdf file (with expo-file-system)

**Comment by SheldonReay** [comment]
> Maybe the PDF is too large.
> Are you able to use a smaller PDF to isolate the issue?

Hey, so I was able to open **any size** PDF on an actual physical device running expo. This issue seems to be on the emulator only right now. Ive tried 2 different emulators and they both do the same. 

Maybe this could be something to do with the performance limitations of an emulator?

**Comment by xcarpentier** [comment]
Yes it could be.
