### ISSUE TITLE
Max zoom is too far, how can I increase max zoom?

### ISSUE THREAD

**Issue by Req** [xcarpentier/rn-pdf-reader-js#111]
I have very detailed vector maps as PDFs. Even if I zoom to the closest I can level using the plus zoom button and then pinch zoom as close as I can I can't make out the details and smallest text. Is there any way to zoom closer?

**Comment by xcarpentier** [comment]
Hi!
We can add a prop to increase the pinch-zoom like `maximumScale`?

**Comment by Req** [comment]
@xcarpentier That is better than nothing if it enables us to zoom closer, but if I can see correctly, that only zooms in on an already rasterized image, causing a very blurry outcome -- a true closer zoom would be much better.

**Comment by xcarpentier** [comment]
I can also increase it here https://github.com/xcarpentier/rn-pdf-reader-js/blob/master/react-pdf/Reader.tsx#L56
I can do both.

**Comment by xcarpentier** [comment]
Fix in v4.1.0
