### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by superyarik** [xcarpentier/rn-pdf-reader-js#112]
as i see there is webview inside with external libs from CDN. so, it does't work in offline. Do you plain to include libs to bundle and making possible offline work?

**Comment by xcarpentier** [comment]
Maybe => https://github.com/xcarpentier/rn-pdf-reader-js/pull/113

**Comment by franknmungai** [comment]
So offline mode now fully works in the new upgrade, is it out in the latest npm version yet?

**Comment by brianchenault** [comment]
This is a huge issue for me, as my app needs to support offline viewing of PDFs. Any update on this? Thanks!

**Comment by LordMilan** [comment]
So does the pdf works in offline mode now??? after making changes to index.tsx of rn-pdf-reader???

**Comment by xcarpentier** [comment]
No, don’t have time to do it, I’ll accept a PR

**Comment by stratoss** [comment]
@xcarpentier I'm pretty new to react, but can try to help out with the offline mode. Can you give me a quick  hint around the tool-chain used to compile / test the code?

I can see that in the npm package rn-pdf-reader-js the problematic code is contained in lib/index.js while in this repo is located at src/index.tsx .

Thank you in advance!
