### ISSUE TITLE
PDF renders as blank screen on Android 9 with Expo SDK 38.0.0

### ISSUE THREAD

**Issue by nkumar-ee** [xcarpentier/rn-pdf-reader-js#120]
#### Issue Description
The PDF renders a blank screen when tried rendering in Android 9 Devices (Pixel 3a, Pixel 2, Nexus 6)

#### Steps to Reproduce / Code Snippets
```
import React, { useState, useEffect } from 'react';
import PDFReader from 'rn-pdf-reader-js';
import { getDownloadURL } from '../../graphql';

export const PdfViewer = ({ id }) => {
  const [data, setData] = useState(null);
  useEffect(() => {
    getDownloadURL({ id: id }).then((res) => {
      fetch(res.data.downloadUrl)
        .then((res) => res.blob())
        .then((blob) => {
          var reader = new FileReader();
          reader.readAsDataURL(blob);
          reader.onloadend = function () {
            setData(reader.result);
          };
        });
    });
  }, [id]);
  
  return (
    <>
      <PDFReader
        style={{ flex: 1 }}
        source={{
          base64: data.replace('octet-stream', 'pdf'),
        }}
      />
    </>
  );
};
```

#### Expected Results
Android 9
<img width="400" alt="Screenshot 2020-08-04 at 2 55 51 PM" src="https://user-images.githubusercontent.com/53217214/89277681-c9436e00-d662-11ea-9581-3d1f11dfff09.png">

IOS
<img width="428" alt="Screenshot 2020-08-04 at 2 54 18 PM" src="https://user-images.githubusercontent.com/53217214/89277695-ce082200-d662-11ea-9e89-72c500fb6c42.png">

#### Additional Information

* Nodejs version: "14.5.0"
* React version: "16.11.0"
* React Native version: "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
* rn-pdf-reader-js version: 4.1.1
* Platform(s) (iOS, Android, or both?): Android (SDK 28)
* TypeScript version: NA

#### Peer dependencies
"expo": "38.0.0",
"expo-constants": "9.1.1",
"expo-file-system": "9.0.1",
"react-native-webview": "9.4.0"

**Comment by deck2k** [comment]
I have the same problem, since the last build, reproduced in Andorid 10, 9 and 8. In iOS it works without problems.  We await the solution of the same, thank you very much

**Comment by oliuradu** [comment]
+1

**Comment by deck2k** [comment]
Workaround

change the app.json to 
"rn-pdf-reader-js": "^4.1.1"

 and  run "yarn install", verify that install version is lastest

**Comment by SirPhemmiey** [comment]
@deck2k , is `4.1.1` the latest version?

And which expo version do you currently use?

**Comment by SirPhemmiey** [comment]
Confirmed. It works now. Thanks

**Comment by nkumar-ee** [comment]
4.1.1 works for me 👍
