### ISSUE TITLE
PDF doesn't render in Android - No matter the source uri

### ISSUE THREAD

**Issue by SirPhemmiey** [xcarpentier/rn-pdf-reader-js#121]
#### Issue Description
PDF doesn't get rendered in Android but only in iOS. I tried both local file directory and an online pdf file. It only shows on iOS and not on Android.

#### Steps to Reproduce / Code Snippets
```
<PDFReader
           style={{
               width: Dimensions.get("window").width,
                height: Dimensions.get("window").height,
            }}
           source={{
               uri: "http://gahp.net/wp-content/uploads/2017/09/sample.pdf",
           }}
       />
```
#### Additional Information

* React Native version: "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz"
* rn-pdf-reader-js version: "^3.1.0"
* Platform(s) (iOS, Android, or both?): "both"
* TypeScript version: "3.7.5"

I made the same comment [here](https://github.com/xcarpentier/rn-pdf-reader-js/issues/95#issuecomment-669129053)

**Comment by oliuradu** [comment]
+1

**Comment by SirPhemmiey** [comment]
@xcarpentier, could you help, please?

**Comment by SirPhemmiey** [comment]
[This](https://github.com/xcarpentier/rn-pdf-reader-js/issues/120#issuecomment-669334101) helped me.
