### ISSUE TITLE
iOS blank pdf

### ISSUE THREAD

**Issue by T0mAl3x** [xcarpentier/rn-pdf-reader-js#125]
Hello! I’m facing an issue with blank pdf on iOS. On Android works fine.
Output android: URL_TO_BASE64
FilePath: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FDentamarketAdmin-1d201ec7-24e5-44e6-ba76-14734df18548/1603885606637.pdf

Output iOS: DIRECT_URL
FilePath: file:///var/mobile/Containers/Data/Application/75AC183E-1870-4895-BB5D-5610C4AA6714/Library/Caches/ExponentExperienceData/%2540anonymous%252FDentamarketAdmin-1d201ec7-24e5-44e6-ba76-14734df18548/1603885672863.pdf

Additional info:
- expo-file-system to downloadAsync in cache folder
- expo: 38.0.8
- rn-pdf-reader-js: 4.1.1

**Comment by theambidextrous** [comment]
any home on this... i got the same output for iOS but internet files works fine ...

**Comment by T0mAl3x** [comment]
Sorry... I didn't manage to solve it.
Yes, the internet files work fine.
I looked up their code and it looks like it returns DIRECT_URL if the platform is iOS && uri (path to local file in our case) != null which is somehow incorrect. DIRECT_URL is the render type used in another function that builds the process and I don't think is correct. It should be URL_TO_BASE64 like in android.

**Comment by tairosonloa** [comment]
I'm still facing the same issue
