### ISSUE TITLE
How to remove grey border around PDF?

### ISSUE THREAD

**Issue by aes421** [xcarpentier/rn-pdf-reader-js#132]
#### Issue Description

I am trying to remove the gray border than the PDF Viewer renders (I'm on Android using expo)

#### Steps to Reproduce / Code Snippets

<PDFReader
          source={{
            uri: selectedSong,
          }}
          style={{
            flex: 1,
            padding: 0,
            margin: 0,
          }}
        />

#### Expected Results

I expect no border, but it still has a gray border around the entire PDF

#### Additional Information

* React version: 16.13.1
* React Native version: sdk-40.0.1
* rn-pdf-reader-js version: 4.1.1
* TypeScript version: 4.0.0

**Comment by MainoGimenez** [comment]
I am having the same problem, any luck yet?

**Comment by Clumsynite** [comment]
Use the `withScroll` prop

**Comment by thpapei** [comment]
> Use the `withScroll` prop

This doesn't work

**Comment by kamal-hossain** [comment]
I have also failed to remove the grey background. It may help if you really want to remove the grey background from the UI.

```
<PDFReader
 webviewStyle={{ margin: -26  }}
/>
```

**Comment by Nils-Thiele** [comment]
I want to use the customStyle props to change the background for example. But the changes do not affect the display.
