### ISSUE TITLE
How remove + - zoom buttons?

### ISSUE THREAD

**Issue by majidv** [xcarpentier/rn-pdf-reader-js#133]
#### Issue Description

How remove + - zoom buttons?

#### Expected Results

No + - zoom buttons

**Comment by Alexsandrogms** [comment]
> #### Descrição da questão
> Como remover + - botões de zoom?
> 
> #### Resultados esperados
> Não + - botões de zoom

An alternative to remove the buttons

```
<PDFReader 
  source={{...}}
  customStyle={{
    readerContainerZoomContainerButton: {
       display: 'none',
   },
  }}
/>
```
