### ISSUE TITLE
cannot view the pdf when offline

### ISSUE THREAD

**Issue by ZapySolo** [xcarpentier/rn-pdf-reader-js#134]
#### Issue Description

The pdf viewer works fine when online, but when offline the pdf does not render the pdf... I m guessing its cuz of the cdn js libraries that needs to be downloaded.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* rn-pdf-reader-js version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* TypeScript version: [FILL THIS OUT]

**Comment by superyarik** [comment]
there is autoclosed issue
https://github.com/xcarpentier/rn-pdf-reader-js/issues/112

and regarding PR - https://github.com/xcarpentier/rn-pdf-reader-js/pull/130

but all of this auto closed - looks like author not support this lib any more (

**Comment by stratoss** [comment]
It seems so indeed. I've packaged the library with that feature. You can test it with  `npm install bildau/rn-pdf-reader`. The old reader needs to be removed first.
