### ISSUE TITLE
Unable to install rn-pdf-reader-js on expo > 37

### ISSUE THREAD

**Issue by SatyamBansal** [xcarpentier/rn-pdf-reader-js#137]
#### Issue Description

Unable to install rn-pdf-reader-js
I have tried installing it first on expo 38 then on expo 39. Please Help.

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

npm i  rn-pdf-reader-js

#### Expected Results
It should get installed successfully on expo 36+ as mentioned in docs

#### Additional Information

* Nodejs version: v15.1.0
* React Native version: 0.63
* rn-pdf-reader-js version: 4.1.1
* Platform(s) (iOS, Android, or both?): NA
* Expo version: 39.0.0

![image](https://user-images.githubusercontent.com/19202937/109791713-bfa1d900-7c38-11eb-941b-dab9623e413f.png)

**Comment by AbeerAhmad** [comment]
not able to install this dependancy ..facing the same error

**Comment by theambidextrous** [comment]
Did anyone find a solution to this?

**Comment by SatyamBansal** [comment]
Nope, I ended up installing it with --force flag, and somehow it worked. Also for me, it's throwing as an error only on node v15. I tried switching to node v14.16.0 LTS, and now it's only there as a warning not as an error anymore. So now I am using node 14.16.0 LTS for my work.

**Comment by theambidextrous** [comment]
I think the developer should provide a proper fix .. 

I had to get it from another app that was using expo sdk36, then pasted it in node_modules of my sdk40 app, then i went on to download js-base64(which this library depends on ) manually and put it inside the node_modules of this library.

Now it works.

**Comment by Kensidikenny** [comment]
Just install with Yarn. 
Works well in expo 41

**Comment by gregdburns** [comment]
> Just install with Yarn.
> Works well in expo 41

Same here, although using npm.  No issues on Expo v 41.
