### ISSUE TITLE
component doesn't render

### ISSUE THREAD

**Issue by kristkirp** [xcarpentier/rn-pdf-reader-js#15]
Hi i have following versions:

"devDependencies": {
    "jest-expo": "27.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
"dependencies": {
    "expo": "^27.0.0",
    "react": "^16.3.1",
    "react-native": "^0.55.4"
}

"expo": {
    "sdkVersion": "27.0.0",
}

The component doesn't give any error just nothing. The problem is not in uri/base64 they are fine, i tried uri from your example

This is the code:
 KeyboardAvoidingView keyboardVerticalOffset={80} behavior="padding" style={{ flex: 1 }}
                ScrollView style={{ flex: 1 }}
                          View style={{ flex: 1,
                           paddingTop: Constants.statusBarHeight}}>
                                <PDFReader
                                    source={{ uri: "http://gahp.net/wp-content/uploads/2017/09/sample.pdf" }}
                                />
                            View
                            ScrollView
KeyboardAvoidingView

Thank you

upd: the full code not displayed i don't know why, it displays only in edit mode

**Comment by xcarpentier** [comment]
What do you mean by display only on edit mode?

**Comment by kristkirp** [comment]
I updated code in questions, had to remove "<" and "/>" because it doesn't show fully with with them

**Comment by kristkirp** [comment]
So my PDFReader is inside View, ScrollView, KeyboardAvoidingView

**Comment by xcarpentier** [comment]
iOS or android ?
On device or emulator ?
If you use it only into `<View/>` does it works?

For now I recommend to use this component in full screen.

**Comment by xcarpentier** [comment]
Can you provide a screenshot?

**Comment by kristkirp** [comment]
When it is wrapped in just a View it works! Thank you for help! :)

**Comment by xcarpentier** [comment]
Close and add in FAQ: https://github.com/xcarpentier/rn-pdf-reader-js#faq

**Comment by farahanimahendo** [comment]
Hi there, I keep getting this error: "console.error: Unable to get result of file due to bad type, waiting string and getting object."
Could some assist please? I will provide more info if needed.

**Comment by FabienDeborde** [comment]
I am having the same issue as the one described above.
The code was working a few weeks ago and today when I came back to debug another part of the app I realized the PDF Reader was broken.
I tried to render the code below instead to be sure I didn't mess something with my URI but I still code the same error message.
`<PDFReader source={{ uri: 'http://gahp.net/wp-content/uploads/2017/09/sample.pdf' }} />`

Could it be related to the upgrade to expo 31?

**Comment by thiagosouzasi** [comment]
Hello guys, I solved the display problem by adding the following code inside the styles

pdf: {
        width: Dimensions.get ('window'). width,
        height: Dimensions.get ('window'). height,
    },

**Comment by Jayeshkarma** [comment]
`import React, { memo } from 'react';
import { View, StyleSheet, Dimensions } from 'react-native'
import PDFReader from 'rn-pdf-reader-js'
const LearningScreen = props => {

    return( 
      <View style={styles.container}> 
        <PDFReader style={styles.pdf}
          source={{
            uri: 'http://gahp.net/wp-content/uploads/2017/09/sample.pdf',
          }}
        />
      </View> 
    )
}
const styles = StyleSheet.create({
    container:{
          justifyContent:'center',
          flex:1,

          backgroundColor:'red'
      },

      pdf: {
        width: Dimensions.get ('window'). width,
        height: Dimensions.get ('window'). height,
        backgroundColor:'#000'
        },
    });
export default memo(LearningScreen);`



not  showing anything on screen please help me  to solve it

**Comment by xTurbeaux** [comment]
does anyone use the headers? cant get mine to track to the desired destination set on the pdf, honestly Im not even sure if I have this configured properly 


<View style={{width: '100%', height: '100%'}}>
	<PDFReader 
	        source={{
		        uri: 'http://10.1.10.167:5501/docs/Product_Guide_2020.pdf#hearth',
			headers: { ['hearth']: 'http://10.1.10.167:5501/docs/Product_Guide_2020.pdf#hearth' }
		}}
	/>
</View>

**Comment by Vishal-Ramanlal** [comment]
Does the work while the device is offline. The following code is what i use.
`                <PdfReader style={styles.pdf} source={{ uri: path }} />`

the path being from the filesystem i.e. file://path. 
This code works when the device is online however when i turn of data and wifi, it doesn't load the pdf. Any solutions?

**Comment by begumaltunbas** [comment]
Hi I keep getting an error saying: 
"Error: Objects are not valid as a React child (found: object with keys {_40, _65, _55, _72}). If you meant to render a collection of children, use an array instead.]"

I believe my base64 string is correct, it prints like this on console: data:application/pdf;base64,JVBERi0xLjUKJbXtrvsKNCAw.....

 Here is my code im trying to view the pdf received from api on ios.


```
import PDFReader from 'rn-pdf-reader-js'

const InvoiceScreen = async({ route, navigation }) => {

  
  const { invoice_all } = route.params;

  const invoice=invoice_all.invoice;
  const my_uri = "data:application/pdf;base64,"+invoice;


  return (
    <PDFReader
      Source={{
        base64:my_uri ,
      }}
      props={{
        source: Source,
      }}
    />
  )
};

export default InvoiceScreen;

```


Please help me !!! Thanks in advance.

**Comment by monizb** [comment]
> Does the work while the device is offline. The following code is what i use.
> ` <PdfReader style={styles.pdf} source={{ uri: path }} />`
> 
> the path being from the filesystem i.e. file://path.
> This code works when the device is online however when i turn of data and wifi, it doesn't load the pdf. Any solutions?

Were you able to fix this?

**Comment by AlacranBlanco** [comment]
i tried "`<View>`" but it didn't work, but i use a template tag "<>" and it works

**Comment by monizb** [comment]
> Does the work while the device is offline. The following code is what i use.
> ` <PdfReader style={styles.pdf} source={{ uri: path }} />`
> 
> the path being from the filesystem i.e. file://path.
> This code works when the device is online however when i turn of data and wifi, it doesn't load the pdf. Any solutions?

So on closely looking at the code I realized that offline pdf will load from your local file storage but the Pdf viewer itself requires an internet connection to load CDN files, so the device has to be online

**Comment by AlacranBlanco** [comment]
Hi!

**NOTE: Please read docs from EXPO about FileSystem before continue reading this:** https://docs.expo.dev/versions/latest/sdk/filesystem



I did my "best" approach to play the reader OFFLINE/ONLINE loading files `https://` or `file://`;

1 .- You have to download the CDN the first time that user use the APP, then save it in the storage using FileSystem, obviously the first time that our user use the app it has to be ONLINE

I did this in my App.js, this is my first screen to render in my app

![image](https://user-images.githubusercontent.com/51062435/131075485-aa2983d8-5375-4db5-8bb1-836ef36a7a5c.png)

2 .- Then you have to edit the index.js file of the module "rn-pdf-reader-js" like this, this means that were always loading CDN from our device no from internet

![image](https://user-images.githubusercontent.com/51062435/131078489-22d5834e-8eda-4132-8e51-1a5d56384e5e.png)

2.1 .- Edit the HTML like this

![image](https://user-images.githubusercontent.com/51062435/131088690-1555bacf-f9ca-4c53-919a-518a619434ab.png)

3 .- And **voilà**, you can actually render the PDF reader OFFLINE this only works with files that are store in our device (ie. `file://`)

![WhatsApp Image 2021-08-26 at 11 58 22 PM](https://user-images.githubusercontent.com/51062435/131076045-1f366a6c-35c7-4620-b6b3-e8120d73d5ce.jpeg)

**I KNOW THAT THIS IS NOT THE BEST OPTION BUT THIS IS A GOOD WORKAROUND TO SOLVE THIS**

**I KNOW THAT THIS MODULE WILL CHANGE EVERYTIME THAT WE RUN "NPM INSTALL", THIS MEANS THAT "index.js" WILL NOT WORK TILL WE CHANGE IT AGAIN (STEP #2)**

**THANKS TO @monizb for the feedback**

**Comment by monizb** [comment]
That's a brilliant workaround!

**Comment by sylvio-ruiz** [comment]
> Hi!
> 
> **NOTE: Please read docs from EXPO about FileSystem before continue reading this:** https://docs.expo.dev/versions/latest/sdk/filesystem
> 
> I did my "best" approach to play the reader OFFLINE/ONLINE loading files `https://` or `file://`;
> 
> 1 .- You have to download the CDN the first time that user use the APP, then save it in the storage using FileSystem, obviously the first time that our user use the app it has to be ONLINE
> 
> I did this in my App.js, this is my first screen to render in my app
> 
> ![image](https://user-images.githubusercontent.com/51062435/131075485-aa2983d8-5375-4db5-8bb1-836ef36a7a5c.png)
> 
> 2 .- Then you have to edit the index.js file of the module "rn-pdf-reader-js" like this, this means that were always loading CDN from our device no from internet
> 
> ![image](https://user-images.githubusercontent.com/51062435/131078489-22d5834e-8eda-4132-8e51-1a5d56384e5e.png)
> 
> 2.1 .- Edit the HTML like this
> 
> ![image](https://user-images.githubusercontent.com/51062435/131088690-1555bacf-f9ca-4c53-919a-518a619434ab.png)
> 
> 3 .- And **voilà**, you can actually render the PDF reader OFFLINE this only works with files that are store in our device (ie. `file://`)
> 
> ![WhatsApp Image 2021-08-26 at 11 58 22 PM](https://user-images.githubusercontent.com/51062435/131076045-1f366a6c-35c7-4620-b6b3-e8120d73d5ce.jpeg)
> 
> **I KNOW THAT THIS IS NOT THE BEST OPTION BUT THIS IS A GOOD WORKAROUND TO SOLVE THIS**
> 
> **I KNOW THAT THIS MODULE WILL CHANGE EVERYTIME THAT WE RUN "NPM INSTALL", THIS MEANS THAT "index.js" WILL NOT WORK TILL WE CHANGE IT AGAIN (STEP #2)**
> 
> **THANKS TO @monizb for the feedback**

Are you sure that FileSystem.readDirectoryAsync will return an array on the same file order that you dowload them? If not the pdfjsLib.GlobalWorkerOptions.workerSrc can get the wrong destination source. You must to make sure where they are before passing them to the scripts tags and off course to the key (workerSrc) above. So you must to reorder the array.

`await writeAsStringAsync(htmlPath, viewerHtml(data, customStyle, withScroll, withPinchZoom, maximumPinchZoomScale, cndList.sort()));`

So the cdnList will return the alphabetic order, even if it was not, and you will know exactly where is the index for each filepath.

So, if you do not want to change the indexes that you already added to the in the index.js,  just add a prefix to each file when you created them to dowload like rn1-, rn2- , rn3-, rn4-, rn5- and prepend them in each file since they are on the same order that you added them to the index.js, but keep the cndList.sort(), just to be sure they will be where we want.

Another solution is do the same thing that xcaperntier did, embed each js file as base64 on the bundleContainer and call a function to decode the string and write it to a file with a name that you wish and add it to the source of html. In this case, the pdf viewer will work even the user open it first time without a connection. xcarpentier save and remove it when the component will unmount, but you can leave them there.

Good solution, thank you.

Great work!

**Comment by visharma14** [comment]
why my hooks dosent render a pdf by using fetch api in rn-pdf-reader-js . please help i'm new in this native

**Comment by thecompoundingdev** [comment]
@AlacranBlanco 
Hi Alacran! I'm having some trouble displaying the viewer with a base64 pdf. You seem like you've figured this package out pretty well- I'd love to chat with you for a few minutes!

**Comment by alt2cl** [comment]
Is this project compatible with SDK 49?

**Comment by mktspace** [comment]
Seeing error with SDK 49. Has anyone tried using with SDK49. 

Error: Cannot convert value to null object

Works fine with SDK48. WebView package dependency seem like

**Comment by kirtikapadiya** [comment]
@mktspace  I also found same issue on expo SDK 49
 Its not working in android device. 
 Reproducible snack demo : https://snack.expo.dev/@kirtikk/pdfreader-expo-49?platform=android

**Comment by kirtikapadiya** [comment]
> When it is wrapped in just a View it works! Thank you for help! :)
Use Expo SDK 49
Its not working in android device.
Reproducible snack demo : https://snack.expo.dev/@kirtikk/pdfreader-expo-49?platform=android
