### ISSUE TITLE
Cant Run pdf when Offline Mode or just linked file on local server

### ISSUE THREAD

**Issue by Kensidikenny** [xcarpentier/rn-pdf-reader-js#155]
can anyone have a suggestion running this rn-pdf-reader-js offline mode?

**Comment by Kensidikenny** [comment]
I solved This Issue , 
just download the cdnjs file on Node_modules/rn-pdf-reader-js/lib/index.js and create the file on lib file name same on cdnjs or something you want, then change the src .
works fine on Expo 41

**Comment by monizb** [comment]
> I solved This Issue ,
> just download the cdnjs file on Node_modules/rn-pdf-reader-js/lib/index.js and create the file on lib file name same on cdnjs or something you want, then change the src .
> works fine on Expo 41

Hi, could you please help me with this, are you talking about these two files: https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.min.js and https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/web/pdf_viewer.min.js, i see additional three files as well https://unpkg.com/react@16/umd/react.production.min.js , https://unpkg.com/react-dom@16/umd/react-dom.production.min.js, https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/build/pdf.worker.min.js @Kensidikenny

**Comment by monizb** [comment]
@Kensidikenny can you help me out a little with this, still not able to do this

**Comment by monizb** [comment]
I have tried downloading these files and referencing them in the source but they still don't seem to work
