### ISSUE TITLE
Android Webview 92 not displaying pdf

### ISSUE THREAD

**Issue by coloed3** [xcarpentier/rn-pdf-reader-js#158]
#### Issue Description

New update to webview 92 on android only shows headers  and removes the body of the pdf 

#### Steps to Reproduce / Code Snippets

switch webview on android from 91 to 92 or higher 

#### Expected Results
 When  the user attempts to review the pdf it doesn't show 

#### Additional Information
react-moment": "^1.1.1",
  "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
  "react-native-credit-card-input": "^0.4.1",
  "react-native-date-picker": "^3.2.3",
  "react-native-dropdown-picker": "^3.7.0",
  "react-native-fs": "^2.16.6",
  "react-native-gesture-handler": "~1.7.0",
  "react-native-get-random-values": "^1.5.0",
  "react-native-maps": "0.27.1",
  "react-native-modal-selector": "^2.0.3",
  "react-native-open-maps": "^0.3.5",
  "react-native-paper": "^4.0.1",
  "react-native-passkit-wallet": "^0.1.4",
  "react-native-progress-steps": "^1.3.4",
  "react-native-reanimated": "~1.13.0",
  "react-native-safe-area-context": "3.1.4",
  "react-native-screens": "~2.10.1",
  "react-native-scroll-into-view": "^1.0.3",
  "react-native-svg": "12.1.0",
  "react-native-swiper": "^1.6.0",
  "react-native-tab-view": "^2.15.2",
  "react-native-walkthrough-tooltip": "^1.1.11",
  "react-native-wallet": "^1.0.8",
  "react-native-web": "~0.13.7",
  "react-native-webview": "10.7.0",
  "react-number-format": "^4.4.1",
  "reflect-metadata": "^0.1.13",
  "rn-fetch-blob": "^0.12.0",
  "rn-pdf-reader-js": "^4.1.1",
  "styled-components": "^5.3.0",
  "uuid": "^8.3.1",
  "yup": "^0.29.3",
  "yup-phone": "^1.2.12"
},
"devDependencies": {
  "@babel/core": "^7.8.6",
  "@types/base-64": "^0.1.3",
  "@types/react": "~16.9.35",
  "@types/react-native": "~0.63.2",
  "@types/yup": "^0.29.7",
  "babel-preset-expo": "^8.3.0",
  "jest-expo": "^39.0.0",
  "typescript": "~3.9.2"

**Comment by aytaceminoglu** [comment]
Same problem here. 

Any temporal solution?

**Comment by aytaceminoglu** [comment]
I solved with
`useGoogleReader={Platform.OS == "ios" ? false : true}`
