### ISSUE TITLE
android white pages when from base64, ios fine

### ISSUE THREAD

**Issue by kristkirp** [xcarpentier/rn-pdf-reader-js#16]
It works perfectly on ios, it's android only problem, number of pages is correct, but pages are white
![screenshot_20180614-102752](https://user-images.githubusercontent.com/30670856/41418602-091c807e-6fbe-11e8-9406-7bd02642da58.png)

**Comment by xcarpentier** [comment]
Is your file contains only images?

**Comment by kristkirp** [comment]
It contains simple pdf document without pictures

**Comment by xcarpentier** [comment]
Can you provide a PDF link to test in my side?

**Comment by xcarpentier** [comment]
I change the limitation on this package too: 
https://github.com/xcarpentier/rn-pdf-reader-js#limitations

**Comment by kristkirp** [comment]
Sorry, just realized the file was corrupted, with other pdfs everything is perfect, thank you for this component!
