### ISSUE TITLE
how to use relative path,

### ISSUE THREAD

**Issue by echolove38** [xcarpentier/rn-pdf-reader-js#161]
the following is my code:
`Asset.fromModule(require('../../../assets/big_buck_bunny.mp4')).uri`
but can't run.
so , how to use local assets file

**Comment by SiddheshNan** [comment]
Hello, I have used the following to read the local asset file:
`
const file = Asset.fromModule(require("../docs/myfile.pdf"));
file.downloadAsync().then((doc) => {
        setState({  localFilePath: doc.localUri });
})
`
