### ISSUE TITLE
View doc, xls, ppt, etc

### ISSUE THREAD

**Issue by kristkirp** [xcarpentier/rn-pdf-reader-js#17]
Hi, I thought it'd be great if there'd be something like react-native-doc-viewer compatible with expo, 
Your component is the only available to view pdf and compatible with expo,
So, may be you may like to consider extending to other formats :)

**Comment by xcarpentier** [comment]
Good point, thank you.

But for now I should improve this reader for android, as you can see there are some possible improvement: add zoom ability, add image ability, ...

If you want to help don't hesitate to create PR or give some suggestion, we are more strong together ;)

Thanks!

**Comment by tofoli** [comment]
Waiting for zoom capability
