### ISSUE TITLE
Remove log. 

### ISSUE THREAD

**Issue by SupaMario123** [xcarpentier/rn-pdf-reader-js#171]
Hello, 
thank you very much for this awesome package! It solves my problem. 
Just one note. 
Please remove the Log "URL_TO_BASE64" every time displayed, when opening a pdf with it. 

Thank you!

<img width="269" alt="Bildschirmfoto 2022-03-12 um 14 25 52" src="https://user-images.githubusercontent.com/33687577/158019758-7a4c2e67-ebf6-42df-83ec-ca1759e172ae.png">

**Comment by sylvio-ruiz** [comment]
This is just a debug log before mount the component. You can avoid it going to your node-modules path/rn-pdf-reader-js/lib, opening the index.js and commenting the line around 229 :
    componentDidMount() {
        this.setState({ renderType: this.getRenderType() }, () => {
            //console.debug(this.state.renderType);
            this.validate();
            this.init();
        });
    }

**Comment by sylvio-ruiz** [comment]
> Hello, thank you very much for this awesome package! It solves my problem. Just one note. Please remove the Log "URL_TO_BASE64" every time displayed, when opening a pdf with it.
> 
> Thank you!
> 
> <img alt="Bildschirmfoto 2022-03-12 um 14 25 52" width="269" src="https://user-images.githubusercontent.com/33687577/158019758-7a4c2e67-ebf6-42df-83ec-ca1759e172ae.png">

This is just a debug log before mount the component. You can avoid it going to your node-modules path/rn-pdf-reader-js/lib, opening the index.js and commenting the line around 229 :
componentDidMount() {
this.setState({ renderType: this.getRenderType() }, () => {
//console.debug(this.state.renderType);
this.validate();
this.init();
});
}

**Comment by SupaMario123** [comment]
Thank you! 
I dont have the log any more. Should i leave the "Issue" open for you as a reminder to remove log ?

**Comment by sylvio-ruiz** [comment]
> Thank you! I dont have the log any more. Should i leave the "Issue" open for you as a reminder to remove log ?

I am happy to know.

I believe that you can leave it as it is. A flag to pass to the component as a prop to show logs is the best option. There are many others when something goes wrong but they are useful when we are developing and testing the code locally. A flag to disable the logs is welcome for production.
