### ISSUE TITLE
rn-pdf-reader-js not working with react native expo SDK 49 in android.

### ISSUE THREAD

**Issue by kirtikapadiya** [xcarpentier/rn-pdf-reader-js#200]
PDF reader not working after updating  expo SDK 48 to expo SDK 49 in android device.

Reproducible snack link : https://snack.expo.dev/@kirtikk/pdfreader-expo-49
same issue : https://github.com/xcarpentier/rn-pdf-reader-js/issues/15
* Nodejs version: 18.12.0
* React version: 18.2.0
* React Native version: 0.72.6
* rn-pdf-reader-js version: 4.1.1
* Platform(s) (iOS, Android, or both?): both
* Expo version: 49.0.0

Error : Cannot convert null value to object

**Comment by MateusArenas** [comment]
try this to resolve:

```
import PDFReader, { Props } from 'rn-pdf-reader-js'

class MyPDFReader extends PDFReader {
  constructor(props: Props | Readonly<Props>) {
    super(props);
    this.state = { ...this.state, renderedOnce: true };
  }
}

....

return (
   <MyPDFReader 
       source={{ uri: uri }}
       ....
   />
)
```

**Comment by kirtikapadiya** [comment]
> try this to resolve:
> 
> ```
> import PDFReader, { Props } from 'rn-pdf-reader-js'
> 
> class MyPDFReader extends PDFReader {
>   constructor(props: Props | Readonly<Props>) {
>     super(props);
>     this.state = { ...this.state, renderedOnce: true };
>   }
> }
> 
> ....
> 
> return (
>    <MyPDFReader 
>        source={{ uri: uri }}
>        ....
>    />
> )
> ```

not working

**Comment by kirtikapadiya** [comment]
Anyways I used another package react-native-pdf for view/render PDF.

**Comment by MarcoGennaro** [comment]
I have the same problem reported on this issue, there is any solution?

**Comment by id-linksoluciones** [comment]
> Anyways I used another package react-native-pdf for view/render PDF.

Can you tell us what package you used, please?

**Comment by MarcoGennaro** [comment]
It's called exactly react-native-pdf, i replace it too in my project with success.
the only problem is that doesn't work with expo go and to test the page where it is used you had to do a development build.

**Comment by ErickNuup** [comment]
> try this to resolve:
> 
> ```
> import PDFReader, { Props } from 'rn-pdf-reader-js'
> 
> class MyPDFReader extends PDFReader {
>   constructor(props: Props | Readonly<Props>) {
>     super(props);
>     this.state = { ...this.state, renderedOnce: true };
>   }
> }
> 
> ....
> 
> return (
>    <MyPDFReader 
>        source={{ uri: uri }}
>        ....
>    />
> )
> ```

This resolve problem expo SDK 50

**Comment by j-q-in-berlin** [comment]
I get the error directly after running "npm install rn-pdf-reader-js". The proposed solutions don't work in my case. Anyone else had the same problem?

**Comment by oussamanm** [comment]
> try this to resolve:
> 
> ```
> import PDFReader, { Props } from 'rn-pdf-reader-js'
> 
> class MyPDFReader extends PDFReader {
>   constructor(props: Props | Readonly<Props>) {
>     super(props);
>     this.state = { ...this.state, renderedOnce: true };
>   }
> }
> 
> ....
> 
> return (
>    <MyPDFReader 
>        source={{ uri: uri }}
>        ....
>    />
> )
> ```
@MateusArenas
its worked after hours of errors , Thanks bro
