### ISSUE TITLE
Printing capabilities?

### ISSUE THREAD

**Issue by themakerman** [xcarpentier/rn-pdf-reader-js#27]
Can print on android/iOS?

**Comment by xcarpentier** [comment]
Hi @themakerman !
Thank for asking ;)

Actually I guess you can use this from expo: https://docs.expo.io/versions/latest/sdk/print

BTW it's a good feature request, I can imagine a small printer icon somewhere and do it for you ! 👍

**Comment by themakerman** [comment]
@xcarpentier if i am free can do a PR. That way it will print like out of the box from same view instead of going back and trigerring expo print API :)

**Comment by xcarpentier** [comment]
https://slack.reactnative.gallery/
