### ISSUE TITLE
Fails on Expo SDK 31 since React Native v56

### ISSUE THREAD

**Issue by iChaosren** [xcarpentier/rn-pdf-reader-js#30]
Throws an error on Expo v31.
We've tried using the file locally and remotely, but we can't open the pdf on either android or ios.

I believe this is due to the changes made since 31 was released:
https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49

If you look further down, you should see a section adding, 
"Base64 encoding support for FileSystem module"

**Comment by iChaosren** [comment]
Sorry I didn't respond after I found the issue, but sadly it seems that the way the pdf reader works has been stopped in the latest version of react-native:
[React Native v56 Change Logs](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#webview-will-only-load-https-urls-by-default)
[iOS no longer supports `file://`](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#ios-specific-changes-3)

So my solution was to upload my pdf file to a site and then use `WebView` on iOS and use the react native `Linking` api to open the pdf url on Android specifically.

Hope this helps...

**Comment by jkeam** [comment]
Does this fix it for you?  https://github.com/facebook/react-native/issues/20835
