### ISSUE TITLE
Component does not render...........help please

### ISSUE THREAD

**Issue by Sanj98** [xcarpentier/rn-pdf-reader-js#32]
Hi 
The component does not render and your index.js file throws errors as below
which says "[js] 'types' can only be used in a .ts file."
![erros](https://user-images.githubusercontent.com/39040972/50440928-55859f00-091e-11e9-82d3-fab5e708a245.PNG)

PLEASE HELP ME OUT

_Originally posted by @Sanj98 in https://github.com/xcarpentier/rn-pdf-reader-js/issues/15#issuecomment-449937356_

**Comment by xcarpentier** [comment]
Should be fixed with v0.2.0
