### ISSUE TITLE
Dont work (on newest Expo version)

### ISSUE THREAD

**Issue by PAKOTxx** [xcarpentier/rn-pdf-reader-js#35]
Dont work (on newest Expo version). How can I fix this? Maby some solution?

**Comment by robputer** [comment]
Also experiencing issues with newer Expo

**Comment by vihpalca** [comment]
show any error message?

**Comment by PAKOTxx** [comment]
Component didnt rendering at all, white screen

**Comment by xcarpentier** [comment]
Sorry about that... will try to find time to fix it this month

**Comment by hughbe** [comment]
Has anyone figured out a workaround?

**Comment by jacobarvidsson** [comment]
I think the iOS component WebView no longer supports local files, I am guessing this still works on Android.

**Comment by a-fortunato** [comment]
We're having problems too, and it's not working on Android either.
The PDF doesn't load (empty screen) and the following warning appears:

`Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_ACCESS_DENIED",
  "loading": false,
  "target": 8205,
  "title": "",
  "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540project-rn%252F/index.html",
}
`

We're using Expo SDK v32.

**Comment by xcarpentier** [comment]
Yes I know!
I don't have time to fix it. If someone can handle it?
PRs are welcome !

**Comment by fredriksebek** [comment]
Here is a solution for those facing on Android:

> Encountered an error loading page, Object { "canGoBack": false, "canGoForward": false, "code": -1, "description": "net::ERR_ACCESS_DENIED", "loading": false, "target": 8205, "title": "", "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540project-rn%252F/index.html", 


node_modules/rn-pdf-reader-js/index.js
Simply add allowFileAccess={true} in the WebView components.

[Reference](https://github.com/facebook/react-native/commit/0c576ef84a1c7f79b228f205cc687ab1b945bda1)

**Comment by xcarpentier** [comment]
Just added it: https://github.com/xcarpentier/rn-pdf-reader-js/commit/f5ecbfdd64e4d7f944267ff93bcaa72b3e78dfe7

**Comment by 0duaht** [comment]
@xcarpentier when you can, could you review #37? Fixes the problem here

**Comment by luongbeta2** [comment]
Hi @xcarpentier 
the bug still happen on **iphone 6s** (ios version 12.1.2), although I used the your version **0.2.1**
Please recheck the issue, thanks !
![iphone 6s](https://user-images.githubusercontent.com/7919490/52555313-ed324480-2e1b-11e9-9ba7-15f985dffa68.jpg)

**Comment by xcarpentier** [comment]
Can you please show me your code?
