### ISSUE TITLE
PDF showing blank

### ISSUE THREAD

**Issue by luongbeta2** [xcarpentier/rn-pdf-reader-js#42]
Hi @xcarpentier 
the bug still happen on **iphone 6s** (ios version 12.1.2), although I used the your version **0.2.1**
(I tested the bug on iphone 5s, it was fixed)
Please recheck the issue, thanks !
![iphone 6s](https://user-images.githubusercontent.com/7919490/52555313-ed324480-2e1b-11e9-9ba7-15f985dffa68.jpg)

_Originally posted by @luongbeta2 in https://github.com/xcarpentier/rn-pdf-reader-js/issues/35#issuecomment-462267039_

**Comment by xcarpentier** [comment]
Can you please show me your code?

**Comment by luongbeta2** [comment]
@xcarpentier 
Hi,  this is my code:
`import { Button, View } from '@shoutem/ui'
import { Colors, Metrics } from '@app/assets'
import { APP_CONFIG } from '@app/constants'
import { Feather } from '@expo/vector-icons'
import { Modal } from 'react-native'
import PDFReader from 'rn-pdf-reader-js'
import R from 'ramda'
import React from 'react'
import TransformableImage from 'react-native-transformable-image'

const styles = {
  closeContainer: {
    backgroundColor: '#f8f8f8aa',
    height: 40,
    width: 40,
    position: 'absolute',
    top: 30,
    right: 10
  }
}
export default ({ uri, isShowingModal, isPdf, onCloseModal }) => {
  const shouldShowModal = isShowingModal && uri != null
  return (
    <Modal
      animationType='slide'
      visible={shouldShowModal}
      onRequestClose={onCloseModal}
    >
      <View styleName='flexible'>
        {
          <PDFReader
              source={{ uri }}
              style={{flex: 1, marginTop: 20}}
            />
        }
      </View>

      <View style={styles.closeContainer}>
        <Button
          style={{backgroundColor: Colors.transparent}}
          styleName='flexible tight'
          onPress={onCloseModal}
        >
          <Feather color={Colors.B4T_BLUE} name='x' size={20} style={{fontWeight: 'bold'}} />
        </Button>
      </View>
    </Modal>
  )
}`

**Comment by SaravanakumarSubramanian** [comment]
I am facing the same issue Pdf not displayed in modal screen(Android),
![screenshot from 2019-02-16 21-32-42](https://user-images.githubusercontent.com/7057416/52868426-5215d380-3169-11e9-9c58-6c95b782a27c.png)

**Comment by Amsvartner** [comment]
I'm having the same problem, any news on this? :)

I'm using the example code from the project and the following dependencies.

```
"dependencies": {
    "expo": "^35.0.0",
    "expo-application": "~1.0.0",
    "expo-constants": "~7.0.0",
    "expo-device": "~1.0.0",
    "expo-file-system": "~7.0.0",
    "expo-localization": "~7.0.0",
    "react": "^16.10.2",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-cli": "^2.0.1",
    "react-native-expo-viewport-units": "^0.0.8",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-signature-canvas": "^1.5.1",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.4",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-starter-kit": "^0.7.0",
    "redux-thunk": "^2.3.0",
    "rn-pdf-reader-js": "^0.3.0"
  }
```

**Comment by xcarpentier** [comment]
I think v0.6.0 fixed the issue.
Please let me know if this is not the case.
