### ISSUE TITLE
Use headers in the source

### ISSUE THREAD

**Issue by alexborton** [xcarpentier/rn-pdf-reader-js#47]
This looks like a great solution for me, but i have to authenticate my user in order to allow them to see documents. I do this in iOS by passing in additional `headers` with a Bearer accessToken.

Can this be added to the fetching of the PDF document for Android? I had a brief look under the hood and looks like you do use the `WebView` in there at some point, so we _should_ be able to pass in additional headers if required?

**Comment by dhcmega** [comment]
Hi, any news on this? thanks!

**Comment by xcarpentier** [comment]
Should be fixed at `v0.5.0`.

**Comment by xcarpentier** [comment]
see `webviewProps`
