### ISSUE TITLE
Doesn't work for local files

### ISSUE THREAD

**Issue by Shincham** [xcarpentier/rn-pdf-reader-js#49]
When you try to open a local file, the component gives the message "source props is not correct" and keeps loading.

I'm just sending a document that is inside a folder on my project.

My call to the PDF Reader:
return (
            <View style={styles.container}>
                <PDFReader
                    source={{ uri: "../../assets/doc/bio_security_measurements.pdf" }}
                />
            </View>
        )

My Package.json

{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "expo-cli": "^2.15.3",
    "lodash": "latest",
    "native-base": "^2.8.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-signature-canvas": "^1.3.0",
    "react-navigation": "^2.18.0",
    "rn-pdf-reader-js": "^0.2.3"
  }
}

**Comment by cedms** [comment]
I have the same problem. Does anyone succeed on to make it work with local files?

**Comment by Shincham** [comment]
It will not work ... i checked the code and it tries to open the local file with an xmlHttpRequest method ... looks like it wasn't implemented or tested with local files. It needs to be implemented.

**Comment by jliphard** [comment]
Works for local files for me on both iOS and Android. Key is to get the base64 string leader correct. The correct string leader to use is in the updated readme.

**Comment by reisap** [comment]
i use on expo 32, but actually not reload file pdf. maybe any suggestion ?
fyi i convert my file into base64 
data:application/pdf;base64,JVBERi0xL...’ (not load)
and try to file:// (not load )

but not load..
android not working.
but ios work smooth. T_T

**Comment by dhcmega** [comment]
Did you make it work on Android? Could it be that this package is abandoned?

**Comment by Shincham** [comment]
For the ones that came here looking for a way to open PDF on projects attached to expo:

I managed to get it work on expo by getting the absolute path of the doc, using the Asset.fromModule method, and passed it as a parameter to the component.
You need to import this class from expo-asset

import { Asset } from 'expo-asset';

render() {
        let absolute_path = Asset.fromModule(require('../../assets/docs/yourfile.pdf')).uri
        return (
            <View style={styles.container}>
                {<PDFReader source={{uri: absolute_path}}/>}
            </View>
        )
    }

the path inside require needs to point correctly to your pdf file.

Btw, I don't know if this package is being updated, so the pdf has some slightly bugs.
But just to notice, he was made to solve the problem of opening the PDF with projects running on Expo. Because expo doesn't have a native pdf reader library and can't use react-native link. If you want to open pdf on Android in a project that is not attached to expo, I recommend using this package https://www.npmjs.com/package/react-native-pdf
