### ISSUE TITLE
Display simple pdf on android like iOS when there is only one screeen

### ISSUE THREAD

**Issue by XeeshanAnsari** [xcarpentier/rn-pdf-reader-js#58]
Thanks for the awesome component. Is there possible to remove the extra file option on android like remove plus and minus buttons and up, down arrow buttons on bottom and page counter on top.

iOS seems okay. It is happening on android because of allowFileAccess webView props. but is there any workaround to remove the extra content.

Thanks

**Comment by xcarpentier** [comment]
No this is the reason why we have this lib...
