### ISSUE TITLE
Add support for Incognito mode

### ISSUE THREAD

**Issue by lewatt23** [xcarpentier/rn-pdf-reader-js#61]
Hello, Kudos to the team of rn-pdf-reader-js I love it!.
I wanted to ask that since this lib uses WebView,  will it be possible to add support for incognito mode?. Cause am trying to stop users from taking screenshots some pdf's, If is possible I will be willing to do the PR myself if the team is too busy to do that.

**Comment by xcarpentier** [comment]
What do you mean exactly?
I wonder to understand what is an incognito mode...

**Comment by xcarpentier** [comment]
You are able to specify any WebView props, please read the [README](https://github.com/xcarpentier/rn-pdf-reader-js#props)
