### ISSUE TITLE
Upgrading to expo SDK 34 seems to break it?

### ISSUE THREAD

**Issue by JarrydSaf** [xcarpentier/rn-pdf-reader-js#63]
Get this when using the rn-pdf-reader-js upon opening simulation.

![Screen Shot 2019-08-02 at 4 22 20 pm](https://user-images.githubusercontent.com/12060853/62349017-d1de0180-b541-11e9-8457-bf586471a946.png)

When removing rn-pdf-reader-js app runs normally. Anyone else getting this issue? on pdf-reader-js@0.2.3.

**Comment by magnushavbrandt** [comment]
Yes! I'm having the same issue. I get the same issue with 0.3.0 as well.
It would be awesome to get this fixed. Good library by the way!

**Comment by jliphard** [comment]
You need to patch 0.3.0. Just convert to new syntax (import * as FileSystem from 'expo-file-system') and you will be fine on both iOS and Android.

**Comment by JarrydSaf** [comment]
Still no luck unfortunately. Patched to 0.3.0 and added the import to the .js file I use the PDF reader in, is that what you meant? Cheers.

**Comment by jliphard** [comment]
No - you need to edit index.js within the reader code.

On Aug 5, 2019, at 8:39 AM, Jarryd <notifications@github.com<mailto:notifications@github.com>> wrote:


Still no luck unfortunately. Patched to 0.3.0 and added the import to the .js file I use the PDF reader in, is that what you meant? Cheers.

**Comment by JarrydSaf** [comment]
I couldn't use the new 'install' commands for expo, I think because my expo-cli has been refusing to update for months. I finally re-installed npm/node/yarn/expo and the pdf reader now seems to be working fine. Cheers!
