### ISSUE TITLE
"Sorry an error occurred" launching the example code

### ISSUE THREAD

**Issue by giacomocerquone** [xcarpentier/rn-pdf-reader-js#67]
Hi, trying out this module in a snack: https://snack.expo.io/@giacomocerquone/pdf-reader
I obtain "Sorry an error occurred", how so? I'm using sdk 33

**Comment by dhcmega** [comment]
It seems that the example is for SDK27

**Comment by sguha00** [comment]
Is there a reason it wouldn't run in a newer Expo?

**Comment by xcarpentier** [comment]
Should be fixed on `v0.5.1`.
