### ISSUE TITLE
cannot suport expo 34 sdk

### ISSUE THREAD

**Issue by lazarid** [xcarpentier/rn-pdf-reader-js#69]

**Comment by dellwatson** [comment]
same using expo 34, cant use it as well

**Comment by norezark** [comment]
I installed 'react-native-webview' and edited node_modules/rn-pdf-reader-js/index.js like this

```
// @flow
import React, { Component } from 'react'
import {
  View,
  ActivityIndicator,
  Platform,
  StyleSheet,
} from 'react-native'
import { WebView } from 'react-native-webview'
import * as FileSystem from 'expo-file-system'
import Constants from 'expo-constants'

...
```

Then it worked.

**Comment by yaron1m** [comment]
Even after fixing the imports, I get errors on Android device:
```
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_ACCESS_DENIED",
  "loading": false,
  "target": 975,
  "title": "Webpage not available",
  "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540<MY_APP_NAME>/index.html",
}
```

**Comment by YoniWitz** [comment]
> import 'WebView' from 'react-native' for android
@yaron1m  can you please elaborate? maybe provide the code? I simply don't understand where or how you would use webview with PdfReader
Also, WebView is no longer included in react-native for android either
