### ISSUE TITLE
Exception Thrown When Rendering Base64 Encoded PDFs (iOS)

### ISSUE THREAD

**Issue by pachun** [xcarpentier/rn-pdf-reader-js#74]
```javascript
<PDFReader
  source={{
    base64: `data:application/pdf;base64,${data}`,
  }}
/>
```

The "data" variable is [set to this value](https://gist.githubusercontent.com/pachun/a07e97b98b51b5d9155c868ef7100fa4/raw/677088f9d6fac149432873a8a04b2cbd4a2bfaee/data).

![https://i.imgur.com/uoozswR.png](https://i.imgur.com/uoozswR.png)

It's also worth noting that I'm using [your latest merged commit on master, which updates the code to work well with Expo SDK 34](https://github.com/xcarpentier/rn-pdf-reader-js/commit/db9d5587e9579053b8aa5506e38ccdde95652627). (My project uses Expo SDK 35).

**Comment by xcarpentier** [comment]
Should be fixed at `v0.5.0`.
