### ISSUE TITLE
How do i build and test this project?

### ISSUE THREAD

**Issue by degamer106** [xcarpentier/rn-pdf-reader-js#75]
Hi,

I'm trying to troubleshoot an issue in this project and would like to build it.  What are the steps required to do so?  I'm not seeing any instructions anywhere.

**Comment by degamer106** [comment]
Bring
Up
My
Post

:)

**Comment by degamer106** [comment]
@xcarpentier Hi do you have any instructions?

**Comment by xcarpentier** [comment]
I think v0.6.0 fixed the issue.
Please let me know if this is not the case.
