### ISSUE TITLE
Android 9 - Not able to view 1st and 3rd page on PDF

### ISSUE THREAD

**Issue by degamer106** [xcarpentier/rn-pdf-reader-js#76]
Hi,

When viewing a 7 page PDF on a phone running Android 9, I'm not able to see the 1st and 3rd page of the PDF when it first loads.  If I zoom in all the way, and then navigate through each page, then I'm able to see everything properly.  Is this a known issue?

Thanks.

**Comment by ihranova** [comment]
Yes, I have same issue on Android. How do I fix?

**Comment by degamer106** [comment]
Bring
Up
My
Post

:)

**Comment by degamer106** [comment]
@xcarpentier Hi do you know if any users have encoutered this?

**Comment by xcarpentier** [comment]
Please try `v0.5.0`.

**Comment by xcarpentier** [comment]
I think v0.6.0 fixed the issue.
Please let me know if this is not the case.
