### ISSUE TITLE
Is it possible to set the min / max zoom on Android?

### ISSUE THREAD

**Issue by selvinkuik** [xcarpentier/rn-pdf-reader-js#78]
See the screenshot below of a PDF I am embedding in to my app. On Android, this is the most "zoomed out" I can get, yet the file still does not fit in the screen.

![image001](https://user-images.githubusercontent.com/3469560/67199575-8842db80-f3f9-11e9-8c15-d08e1684e5fc.jpg)

**Comment by xcarpentier** [comment]
This is a good idea!

**Comment by xcarpentier** [comment]
Can you please try the last version ?
