### ISSUE TITLE
What should i return when the file doesn't exist

### ISSUE THREAD

**Issue by rodrigo-martinezd** [xcarpentier/rn-pdf-reader-js#79]
Hello,

What should I return when there is no file so that the library can handle it or throw an exception?.  it would be enough to return a 404 error with a ContentType of application/json?

**Comment by xcarpentier** [comment]
Good question!
Please see here an example on how to handle it: https://github.com/xcarpentier/rn-pdf-reader-js/blob/master/App.tsx#L46
