### ISSUE TITLE
Error access denied with local file

### ISSUE THREAD

**Issue by Rohitsaini0444** [xcarpentier/rn-pdf-reader-js#81]
When I open it the first time it displays pdf but when I go back and again try to open it  shows this error.

```
Error  {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_ACCESS_DENIED",
  "loading": false,
  "target": 765,
  "title": "Web page not available",
  "url": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540rohitsaini0444%252FRD/index.html",
}
```

Code: 
```tsx
<PDFReader
  source={{ uri:  "file:///data/user/0/host.exp.exponent/files/ExperienceData/%2hs%252FRD/a.pdf"}}  />
```

**Comment by erbud** [comment]
+1

**Comment by xcarpentier** [comment]
please try last version

**Comment by erbud** [comment]
It is reproduced in version 0.5.3 with Expo SDK 36.

**Comment by erbud** [comment]
This fork https://github.com/Codeko/rn-pdf-reader-js works fine.

**Comment by xcarpentier** [comment]
You should really use the last version, I've made better support for iOS and Android!
Please let me know what I need to change here to fix it. Even if that from 'your' old clone of this repo.

**Comment by erbud** [comment]
> You should really use the last version, I've made better support for iOS and Android!
> Please let me know what I need to change here to fix it. Even if that from 'your' old clone of this repo.

@xcarpentier, sorry if my comment referring to a fork has been inappropriate here. The fork is not mine. If I find the difference between both repositories that corrects the problem, I comment, don't hesitate.

**Comment by xcarpentier** [comment]
No worries, I admit that I let this repo too long without fixing it. But today I'm facing issues with this so I work for it and share.

I think the issue is related to the removing of the HTML from local files. (maybe we can keep it but I don't think it's performant at all).

I remove the HTML file at every mount 
https://github.com/xcarpentier/rn-pdf-reader-js/blob/master/src/index.tsx#L221-L223

And I recreate it every at every mounting. 
https://github.com/xcarpentier/rn-pdf-reader-js/blob/master/src/index.tsx#L225-L235

**Comment by xcarpentier** [comment]
Also, I'm using a `temp` directory [FileSystem.cacheDirectory](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemcachedirectory).

As I said if I remove file at every unmount I wonder if I will not use `FileSystem.documentDirectory`.

**Comment by sguha00** [comment]
I'm able to replicate it with Expo 35 with v0.5.3 on Android

https://snack.expo.io/@trinet/rn-pdf-reader-js

**Comment by xcarpentier** [comment]
Can you please try with v`0.6.0`?

**Comment by xcarpentier** [comment]
I think v0.6.0 fixed the issue.
Please let me know if this is not the case.

**Comment by danigonlinea** [comment]
I can confirm that it is working in Android and iOS, many thanks!
