### ISSUE TITLE
WebWiew removed from React Native 

### ISSUE THREAD

**Issue by saboufarid** [xcarpentier/rn-pdf-reader-js#82]
Hi,

I got an error since I upgrade React Native.
Could you import WebView from react-native-webview  ? It has been removed from React Native.
Thanks 

![Simulator Screen Shot - iPhone XS Max - 2019-12-19 at 10 03 16](https://user-images.githubusercontent.com/39901389/71160191-632ae780-2247-11ea-927e-877658ba5b29.png)

**Comment by cklinx** [comment]
Same here: +1

**Comment by anasanzari** [comment]
+1

**Comment by andriboom** [comment]
+1

**Comment by Yasernova** [comment]
Any idea when this will be published on NPM ?

**Comment by xcarpentier** [comment]
Should be fixed at `v0.5.0`.
