### ISSUE TITLE
Bug when changing base64 

### ISSUE THREAD

**Issue by lkum11** [xcarpentier/rn-pdf-reader-js#83]
The library is working fine when i am setting base64 prop as constant string 'data:application/pdf;base64,JVBERi0xLjMNCiXi48/TDQoNCjEg....' , However it's not working when base64 prop is getting set dynamically. 

Please advice if i am missing something or I need to make some changes.

Here is my code: 

 const base = useSelector(state => state.documentReducer.base);

<PDFReader
                    source={{
                        base64: base 
                    }}
                />

**Comment by xcarpentier** [comment]
It should work on v0.5.3

**Comment by lkum11** [comment]
Hi Xavier,

I am using latest version of "rn-pdf-reader-js" as suggested. 
still no luck :( .

PDFReader is not rendering the dynamic url. It is not getting the latest value which is getting dispatched from the action.

Note: To be sure i have tried rendering the same using 'Text' tag, Please advice.

For your reference i have mentioned all the dependencies i am using.

"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@react-native-community/datetimepicker": "^2.1.0",
    "axios": "^0.19.0",
    "expo": "^35.0.0",
    "expo-constants": "~7.0.0",
    "expo-font": "^7.0.0",
    "expo-local-authentication": "^7.0.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-check-box": "^2.1.7",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-highcharts": "^1.0.2",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-picker-select": "^6.3.3",
    "react-native-reanimated": "~1.2.0",
    "react-native-screens": "~1.0.0-alpha.23",
    "react-native-shaking-text": "^0.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-native-webview": "7.0.5",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.1",
    "react-navigation-header-buttons": "^3.0.3",
    "react-navigation-stack": "^1.10.2",
    "react-navigation-switch-transitioner": "^0.1.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "rn-pdf-reader-js": "^0.5.3"
  },

**Comment by lkum11** [comment]
On addition to that

Here is my code in Reducer file:

import { GET_DOCUMENTS, OPEN_DOCUMENT } from '../../actions/profile/documentAction';

const initialState = {
    documentList: [],
    url: 'data:application/pdf;base64,JVBERi0xLjQKJcOkw7z.......'
};

export default ( state= initialState, action) => {
    switch(action.type){
      case GET_DOCUMENTS:
            return {
                ...state,
                documentList: action.documentList
            };
    case OPEN_DOCUMENT:
        console.log('called');
        return {
            ...state,
            url: action.url
        }
    default:
            return state;
    }
}

Here my code in Action :

export const  downloadDocument = (email,fileName) => {
    return async (dispatch) => {
        try {
            console.log("download document")
            const tokenToBeDecoded = await AsyncStorage.getItem('userData');
            if(tokenToBeDecoded){
                const  { token } = JSON.parse(tokenToBeDecoded);

                const response =  await axios.get(Environment.rootUrl + `/dashboard/customer/document/download?email=${email}&fileName=${fileName}`
                ,{ 
                    responseType: 'blob', //'' | 'arraybuffer' | 'blob' | 'document' | 'json' | 'text';
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/pdf' // 'application/pdf',
                    }
                }); 

                if(response.status !== 200) {
                    throw new Error('Something went wrong!');
                }
                const fileReaderInstance = new FileReader();
                fileReaderInstance.readAsDataURL(response.data); 
                fileReaderInstance.onload = () => {
                    base64data = fileReaderInstance.result;  
                    dispatch({
                        type: OPEN_DOCUMENT, url: base64data 
                    });
                    return 'test';
                }
            }
        } catch (err) {
            throw err;
        }
     }
}


PDFReader is displaying the pdf as per the 'base64' mentioned in the reducer but not getting the updated value when  base64 value is getting dispatched from action file.
It is still showing the old value

Please help.

**Comment by xcarpentier** [comment]
Can you please try with v`0.6.0`?

**Comment by xcarpentier** [comment]
I think v0.6.0 fixed the issue.
Please let me know if this is not the case.

**Comment by lkum11** [comment]
Hi Xavier,

I have upgraded the library to the latest version '"rn-pdf-reader-js": "^0.6.0" and the issue still exist. 
I have found a workaround by returning the data and then using useState, somehow useState is working but not dispatch

Here is my code:

export const  downloadDocument = (customerId,fileName) => {
    return async (dispatch) => {
        try {
            const tokenToBeDecoded = await AsyncStorage.getItem('userData');
            if(tokenToBeDecoded){
                const  { token } = JSON.parse(tokenToBeDecoded);
                //console.log(customerId + " " + fileName)
                let file_ext = fileName.substr(fileName.lastIndexOf('.')+1,fileName.length);
                const response =  await axios.get(Environment.rootUrl + `/dashboard/customer/document/download?customerId=${customerId}&fileName=${fileName}`
                ,{ 
                    responseType: 'blob', 
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': file_ext === 'pdf' ? 'application/pdf' : 'application/octet-stream'
                    }
                }); 

                // const fileReaderInstance = new FileReader();
                // fileReaderInstance.readAsDataURL(response.data); 
                // fileReaderInstance.onload = () => {
                //     base64data = fileReaderInstance.result;  
                //     console.log(base64data);
                //     dispatch({
                //         type: OPEN_DOCUMENT, url: base64data 
                //     });
                // }

                if(response.status !== 200) {
                    throw new Error('Something went wrong!');
                }
                return response.data
            }
        } catch (err) {
            throw err;
        }
     }
}

In rendering:
const [pickedDoc, setPickedDoc] = useState('');

const showDocument = useCallback(async (fileName) => {
        try{
            await dispatch(getCustIDAction.getUserID()).then((customerId) => 
            {  
                  dispatch(documentAction.downloadDocument(customerId,fileName)).then((res) => {
                    let file_ext = fileName.substr(fileName.lastIndexOf('.')+1,fileName.length);

                    const fileReaderInstance = new FileReader();
                    fileReaderInstance.readAsDataURL(res); 
                    fileReaderInstance.onload = () => {
                        base64data = fileReaderInstance.result;  
                        setPickedDoc(base64data);
                        setFile_ext(file_ext);
                        setIsModalVisible(true);
                    }
                })
            }) 
        } catch (err){
            console.log(err.message);
            setError(err.message);
        }
    }, [dispatch]);

                    <PDFReader
                                source={{
                                    base64: pickedDoc
                                }}
                            />


Not working :
const url = useSelector(state => state.documentReducer.url);

Thanks for the quick response.

**Comment by xcarpentier** [comment]
It should be fixed on 0.7.2
