### ISSUE TITLE
Reached the end of the pdf

### ISSUE THREAD

**Issue by saidhappy010** [xcarpentier/rn-pdf-reader-js#85]
Please, is there a way to find out if the user has reached the end of the pdf on android and ios?
thanks.

**Comment by xcarpentier** [comment]
Not yet but this is a good feature.

I think we can consider to add `onReachEnd` props and use `postMessage` from the WebView.

**Comment by saidhappy010** [comment]
does it take a long time to add this feature ?
because I really need it. Or would you at least have something else to help me out for this moment
Thanks.

**Comment by xcarpentier** [comment]
PR are welcome :)
