### ISSUE TITLE
Jest test cases are failing

### ISSUE THREAD

**Issue by thomascamara** [xcarpentier/rn-pdf-reader-js#87]
#### Issue Description

After adding the library to the code, Jest tests are failing with the following error: 

> Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     /Users/thomas.camara/IdeaProjects/megaged-app/node_modules/rn-pdf-reader-js/lib/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token *

Has anyone ever faced this issue? Adding the library to "transformIgnorePatterns" in the package.json file seems to fix it, but it also makes the tests 10x slower.

Thank you!

#### Steps to Reproduce / Code Snippets

Add rn-pdf-reader-js to any testable component.

#### Expected Results

Error will show up:

> Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     /Users/thomas.camara/IdeaProjects/megaged-app/node_modules/rn-pdf-reader-js/lib/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token *

#### Additional Information

* Nodejs version: v10.16.0
* React version: 16.8.3
* React Native version: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
* rn-pdf-reader-js version: ^0.6.0
* Platform(s) (iOS, Android, or both?): jest test cases
* TypeScript version: -

**Comment by xcarpentier** [comment]
Do you try to us `jest.mock('rn-pdf-reader-js', () => 'rn-pdf-reader-js')`?

**Comment by thomascamara** [comment]
I haven't but it did work! Thanks a lot Xavier!
