### ISSUE TITLE
PDF doesn't render

### ISSUE THREAD

**Issue by DanielTate** [xcarpentier/rn-pdf-reader-js#92]
#### Issue Description
Just trying to load a local pdf on ios and get the error

    Encountered an error loading page 

    {
      "target": 48167,
      "canGoBack": false,
      "domain": "NSURLErrorDomain",
      "didFailProvisionalNavigation": true,
      "code": -1100,
      "title": "",
      "loading": false,
      "canGoForward": false,
      "description": "The requested URL was not found on this server.",
      "url": ""
    }

Create a react application in Expo and put the pdf reader in and read a local pdf using source

        <PDFReader
          source={{ uri: file://path/to/pdf.pdf }}
        />

#### Expected Results

The PDF reader works

#### Additional Information

* Expo version: 36
* Nodejs version: 12.12
* React version: 4.0.5
* React Native version: sdk-36
* rn-pdf-reader-js version: what ever is on master
* Platform(s) (iOS, Android, or both?): iOS

**Comment by stevenbrown-85** [comment]
+1 on this. file:// works on Android but not iOS

**Comment by cabhara** [comment]
I haven't tried with iOS, but I'm getting an error in Android. It works on the emulator, but not on the device, because on the device my file will be converted to "asset://xxx.pdf", and the reader only accepts "file://" 

```
import AssetUtils from "expo-asset-utils";
import * as FileSystem from "expo-file-system";
import PDFReader from "rn-pdf-reader-js";
const source = require("../../assets/AAA.pdf");

componentDidMount = async () => {
if (Platform.OS === "android") {
      const file = await AssetUtils.resolveAsync(source);
      this._file_link_to_pdf = file.localUri;
}
 ...

 {Platform.OS === "android" && (
              <PDFReader
                source={{
                  uri: this._file_link_to_pdf
                }}
              />
 )}
```

**Comment by DanielTate** [comment]
Thanks @cabhara that has nothing to do with my issue, possibly you should open another issue.
