### ISSUE TITLE
Pdf not render on Android 6 Simulator

### ISSUE THREAD

**Issue by oillada** [xcarpentier/rn-pdf-reader-js#95]
#### Issue Description
Pdf not rendering on Simulator with Android 6 API 23 simulator.
On iOS simulator, iOS device, android 7.1  and android 10.0 API 29 simulator works great.
I'm using a base64 string to create de PDF, i tried with a uri and get the same result

Android 10.0 API 29
<img width="358" alt="Captura de Pantalla 2020-02-26 a la(s) 15 50 46" src="https://user-images.githubusercontent.com/281594/75377072-e011b780-58af-11ea-8def-b2a924aea846.png">

Android 6 API 23
<img width="361" alt="Captura de Pantalla 2020-02-26 a la(s) 15 50 07" src="https://user-images.githubusercontent.com/281594/75376985-b8baea80-58af-11ea-9bd6-1f41f031a215.png">

**Comment by oillada** [comment]
I'm the only one who have this problem?

**Comment by SirPhemmiey** [comment]
@oillada , any update on this please?

**Comment by SirPhemmiey** [comment]
@oillada @xcarpentier any reason for this please? I am having the same issue. PDF doesn't show on Android but it shows on iOS. And they are both physical devices and not emulators
