### ISSUE TITLE
Some PDFs display raw PDF code, no error

### ISSUE THREAD

**Issue by shawnmitchell** [xcarpentier/rn-pdf-reader-js#97]
#### Issue Description
The code below displays raw PDF code, not the PDF image. onError is not called

[nodisplay.pdf](https://github.com/xcarpentier/rn-pdf-reader-js/files/4284917/nodisplay.pdf)

```
    <PDFReader 
        source={{uri: '...'}} 
        onError={(err) => console.log(err)}
    />
```

![image](https://user-images.githubusercontent.com/3594613/75842230-cc79bb80-5d9d-11ea-9aa6-2c7d9c53eb46.png)

![image](https://user-images.githubusercontent.com/3594613/75842298-eca97a80-5d9d-11ea-96e0-378e59e5ad70.png)

#### Additional Information

* Nodejs version: v12.16.0
* React version: 16.9.0
* React Native version: 0.61.4
* rn-pdf-reader-js version: 0.7.2
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: 3.7.2

**Comment by superyarik** [comment]
same issue

![image](https://user-images.githubusercontent.com/1265590/86924682-75fbff80-c138-11ea-977d-ad92dd6b94e2.png)

**Comment by xcarpentier** [comment]
Hi,
Sorry about that!

**Please upgrade! And I will reopen if still fail.** 

I can't reproduce iOS nor android.

- Android :
<img width="409" alt="Screenshot 2020-07-09 11 35 34" src="https://user-images.githubusercontent.com/923036/87023817-954a6980-c1d8-11ea-94a7-2bbac2a702c7.png">

- iOS :
![Screenshot 2020-07-09 11 36 10](https://user-images.githubusercontent.com/923036/87024048-e78b8a80-c1d8-11ea-8889-4781fd816cf2.png)

**Comment by xcarpentier** [comment]
If you still have an issue like this for a long time consider the sponsoring ;)
